export const problemStatements = [
  {
    "id": "PS-01",
    "title": "Smart Traffic Management System",
    "desc": "Urban areas suffer from high congestion because traffic signals operate on static timers regardless of actual vehicle density. Participants must develop an AI-driven Adaptive Signal Control System that analyzes live traffic feeds to dynamically adjust \"Green Light\" durations. The system should prioritize emergency vehicles (ambulances/fire trucks) and reduce \"dead-time\" at empty intersections.",
    "bullets": [
      "Real-time vehicle count dashboard",
      "Waiting time reduction simulation",
      "Emergency \"Green Wave\" triggering"
    ]
  },
  {
    "id": "PS-02",
    "title": "Railway Ticket Management & Predictive Analysis",
    "desc": "Traditional railway systems struggle with \"Waitlist\" uncertainty and seat wastage. Participants need to create an Intelligent Booking & Prediction Engine. This system should not only manage bookings and cancellations but also use historical data to provide a PNR Confirmation Probability. Additionally, it should suggest \"Alternative Route/Train\" options if the primary choice is unavailable.",
    "bullets": [
      "Functional booking portal with PNR",
      "Waitlist prediction model (>80% accuracy)",
      "Dynamic Seat Allocation algorithm"
    ]
  },
  {
    "id": "PS-03",
    "title": "AI Content Detector",
    "desc": "With the rise of Large Language Models (LLMs), distinguishing between human-written and AI- generated content is critical for academic integrity and misinformation control. Participants must build a Deep Learning Classifier that detects text generated by models like GPT-4, Claude, or Gemini. The tool should provide a \"Perplexity\" score and highlight specific segments likely to be AI- generated.",
    "bullets": [
      "Web interface for text analysis",
      "AI vs Human Probability Score",
      "Model performance report (F1, Precision)"
    ]
  },
  {
    "id": "PS-04",
    "title": "AI-Powered Smart Agriculture (IoT & CV)",
    "desc": "Farmers often face crop loss due to undetected pests or nutrient deficiencies. Participants must build a Crop Health Monitoring System that analyzes images of leaves to identify diseases and recommend specific fertilizers or pesticides. The system should also predict the \"Optimal Harvest Date\" based on historical weather patterns.",
    "bullets": [
      "Mobile app for leaf diagnosis",
      "Soil moisture & weather dashboard"
    ]
  },
  {
    "id": "PS-05",
    "title": "Blockchain-Based Supply Chain for Pharmacy",
    "desc": "The pharmaceutical industry is plagued by counterfeit drugs. Participants are tasked with creating a Transparent Drug Tracking System using Blockchain. Every step from the manufacturer to the local pharmacy must be logged on a ledger to ensure the medicine's authenticity.",
    "bullets": [
      "dApp for \"Chain of Custody\" tracking",
      "Immutable drug storage logs"
    ]
  },
  {
    "id": "PS-06",
    "title": "Personalized Mental Health Chatbot (NLP)",
    "desc": "With rising stress levels, many students don't have immediate access to counseling. Build an Empathetic AI Companion that uses Sentiment Analysis to gauge a user's mood. It should provide coping mechanisms for anxiety/stress and, most importantly, trigger an \"Emergency Alert\" to a human counselor if it detects signs of self-harm.",
    "bullets": [
      "Real-time responsive chat interface",
      "Weekly emotional trend tracker"
    ]
  },
  {
    "id": "PS-07",
    "title": "Fraud Detection in UPI/Digital Payments",
    "desc": "Digital payment fraud is evolving rapidly. Participants must develop a Real-Time Fraud Detection Engine that flags suspicious transactions based on anomalies (e.g., unusual location, sudden high-value transfer, or rapid-fire small transactions).",
    "bullets": [
      "Transaction classification system",
      "False Positive rate report"
    ]
  },
  {
    "id": "PS-08",
    "title": "Automated Resume Screener & Job Matcher",
    "desc": "HR departments receive thousands of resumes that don't match job descriptions (JD). Build a Resume Parser that extracts skills, experience, and education, then ranks candidates based on a \"Match Score\" against a specific JD using Vector Embeddings.",
    "bullets": [
      "Recruiter dashboard for PDF sorting",
      "Candidate \"Skill Gap\" analysis"
    ]
  },
  {
    "id": "PS-09",
    "title": "Decentralized Energy Grid Simulator",
    "desc": "In a smart city, households with solar panels should be able to sell excess electricity to neighbors. Create a P2P Energy Trading Platform that uses a bidding algorithm to balance the local grid's supply and demand without a central authority.",
    "bullets": [
      "Visual energy flow map",
      "Dynamic pricing model"
    ]
  },
  {
    "id": "PS-10",
    "title": "Predictive Healthcare Analytics",
    "desc": "Build a model to predict patient readmission rates using historical medical records and demographic data.",
    "bullets": [
      "Readmission prediction model",
      "Feature importance analysis",
      "Healthcare professional dashboard"
    ]
  },
  {
    "id": "PS-11",
    "title": "Air Quality Index Prediction",
    "desc": "Build a forecasting model for AQI levels in urban areas using meteorological and pollution data.",
    "bullets": [
      "Real-time AQI forecasting model",
      "Spatiotemporal heatmaps",
      "Pollution alert system"
    ]
  },
  {
    "id": "PS-12",
    "title": "Smart Lost and Found System",
    "desc": "Students often lose personal items on campus, and there is no efficient way to report or recover them. Build a platform where users can report lost and found items, upload images, and match items automatically.",
    "bullets": [
      "Functional web/mobile platform",
      "Automated item matching system"
    ]
  },
  {
    "id": "PS-13",
    "title": "Classroom Seat Availability Tracker",
    "desc": "Students waste time searching for empty classrooms or seats. Build a system that shows real-time availability of classrooms or study spaces.",
    "bullets": [
      "Real-time seat availability dashboard",
      "Classroom occupancy tracking system"
    ]
  },
  {
    "id": "PS-14",
    "title": "Smart Event Reminder and Manager",
    "desc": "Students forget important events, deadlines, and meetings. Build an app that allows users to create events and receive reminders with notifications.",
    "bullets": [
      "Event management app with notifications",
      "Calendar synchronization & reminders"
    ]
  },
  {
    "id": "PS-15",
    "title": "Hostel Complaint Management System",
    "desc": "Students face difficulties reporting hostel issues like electricity, water, or maintenance. Build a system to register complaints and track their status.",
    "bullets": [
      "Ticketing system for hostel maintenance",
      "Complaint status tracking dashboard"
    ]
  },
  {
    "id": "PS-16",
    "title": "Study Material Sharing Platform",
    "desc": "Students struggle to find notes, assignments, and previous papers. Build a platform where students can upload, search, and download study materials.",
    "bullets": [
      "Searchable study material repository",
      "File upload & download system"
    ]
  },
  {
    "id": "PS-17",
    "title": "Smart To-Do List with Priority Detection",
    "desc": "Students create to-do lists but cannot prioritize tasks effectively. Build an app that helps users manage tasks and set priorities.",
    "bullets": [
      "Task manager with priority detection",
      "Deadline-based task scheduling"
    ]
  },
  {
    "id": "PS-18",
    "title": "Bus Tracking System for College",
    "desc": "Students do not know the real-time location of college buses. Build a system that shows bus location and expected arrival time.",
    "bullets": [
      "Real-time bus tracking dashboard",
      "ETA prediction & route map"
    ]
  },
  {
    "id": "PS-19",
    "title": "Online Voting System for College Elections",
    "desc": "Manual voting takes time and is difficult to manage. Build a secure online voting platform for college elections.",
    "bullets": [
      "Secure voting portal",
      "Real-time result aggregation"
    ]
  },
  {
    "id": "PS-20",
    "title": "Smart Attendance Tracker",
    "desc": "Students cannot easily track their attendance percentage. Build a system that calculates attendance and alerts students when attendance is low.",
    "bullets": [
      "Attendance dashboard for students",
      "Low-attendance alert system"
    ]
  },
  {
    "id": "PS-21",
    "title": "Daily Expense Tracker for Students",
    "desc": "Students cannot track their daily expenses effectively. Build an app that records expenses and shows spending analysis.",
    "bullets": [
      "Expense logging & analysis app",
      "Spending visualization dashboard"
    ]
  },
  {
    "id": "PS-22",
    "title": "Quiz Platform with Leaderboard",
    "desc": "Students want to practice quizzes and compare performance. Build a quiz platform with scoring and leaderboard.",
    "bullets": [
      "Interactive quiz application",
      "Real-time scoring & leaderboard"
    ]
  },
  {
    "id": "PS-23",
    "title": "Parking Slot Booking System",
    "desc": "Students and staff face difficulty finding parking. Build a system to check and reserve parking slots.",
    "bullets": [
      "Parking reservation platform",
      "Real-time slot availability map"
    ]
  },
  {
    "id": "PS-24",
    "title": "Digital Notice Board",
    "desc": "Students miss important notices. Build a platform where admins can post notices and students receive notifications.",
    "bullets": [
      "Admin notice management portal",
      "Student notification system"
    ]
  },
  {
    "id": "PS-25",
    "title": "Resume Builder Web App",
    "desc": "Students find it difficult to create professional resumes. Build a system that generates resumes from user input.",
    "bullets": [
      "Interactive resume builder tool",
      "PDF resume generation & download"
    ]
  },
  {
    "id": "PS-26",
    "title": "Peer-to-Peer Skill Exchange Platform",
    "desc": "Students want to learn skills from peers. Build a platform where students can teach and learn skills from each other.",
    "bullets": [
      "Skill matching & exchange platform",
      "Peer networking & teaching modules"
    ]
  },
  {
    "id": "PS-27",
    "title": "Smart Classroom Feedback System",
    "desc": "Students cannot easily provide feedback on lectures. Build a platform where students can submit anonymous feedback and faculty can analyze improvements.",
    "bullets": [
      "Anonymous feedback submission portal",
      "Faculty analytics & improvement dashboard"
    ]
  },
  {
    "id": "PS-28",
    "title": "College Club Management System",
    "desc": "Managing club members, events, and registrations manually is inefficient. Build a platform to manage members, events, and participation.",
    "bullets": [
      "Club member & event management portal",
      "Event registration & participation tracking"
    ]
  },
  {
    "id": "PS-29",
    "title": "Smart Internship Tracker",
    "desc": "Students struggle to track internship applications and deadlines. Build a system to manage applications, status, and reminders.",
    "bullets": [
      "Application tracking dashboard",
      "Deadline reminders & status updates"
    ]
  },
  {
    "id": "PS-30",
    "title": "Group Study Room Booking System",
    "desc": "Students face difficulty booking study rooms. Build a system to check availability and reserve rooms.",
    "bullets": [
      "Room availability checker",
      "Online reservation & scheduling system"
    ]
  },
  {
    "id": "PS-31",
    "title": "Digital ID Card System",
    "desc": "Physical ID cards can be lost or damaged. Build a digital ID system with QR code verification.",
    "bullets": [
      "Digital ID card generator",
      "QR code verification system"
    ]
  },
  {
    "id": "PS-32",
    "title": "Smart Grocery List with Budget Control",
    "desc": "People overspend while shopping. Build an app that tracks grocery lists and budgets.",
    "bullets": [
      "Grocery list manager with budget tracking",
      "Spending alerts & budget analysis"
    ]
  },
  {
    "id": "PS-33",
    "title": "Online Doubt Solving Platform",
    "desc": "Students cannot easily get answers to academic doubts. Build a platform where students can post questions and get answers.",
    "bullets": [
      "Q&A forum with topic categorization",
      "Upvoting & best answer selection"
    ]
  },
  {
    "id": "PS-34",
    "title": "Habit Tracker with Streak System",
    "desc": "Users struggle to maintain daily habits. Build an app that tracks habits and motivates users using streaks.",
    "bullets": [
      "Daily habit tracking dashboard",
      "Streak counter & motivational alerts"
    ]
  },
  {
    "id": "PS-35",
    "title": "Smart Medicine Reminder System",
    "desc": "Patients forget to take medicines on time. Build a reminder system with alerts and schedules.",
    "bullets": [
      "Medicine schedule manager",
      "Timely alerts & dosage tracking"
    ]
  },
  {
    "id": "PS-36",
    "title": "Local Event Discovery Platform",
    "desc": "Users miss local events due to lack of information. Build a platform to discover nearby events.",
    "bullets": [
      "Location-based event discovery",
      "Event filtering & notification system"
    ]
  },
  {
    "id": "PS-37",
    "title": "Online Food Donation Platform",
    "desc": "Excess food is wasted while many people need food. Build a platform connecting donors and receivers.",
    "bullets": [
      "Donor & receiver matching system",
      "Food listing & pickup coordination"
    ]
  },
  {
    "id": "PS-38",
    "title": "Smart Password Manager",
    "desc": "Users struggle to remember multiple passwords. Build a secure password storage system.",
    "bullets": [
      "Encrypted password vault",
      "Password generator & strength checker"
    ]
  },
  {
    "id": "PS-39",
    "title": "Online Pet Adoption Platform",
    "desc": "People find it difficult to adopt pets. Build a platform connecting adopters and shelters.",
    "bullets": [
      "Pet listing & search portal",
      "Adoption request & matching system"
    ]
  },
  {
    "id": "PS-40",
    "title": "Digital Queue Management System",
    "desc": "People waste time waiting in queues. Build a system that manages virtual queues.",
    "bullets": [
      "Virtual queue & token system",
      "Real-time wait time estimation"
    ]
  },
  {
    "id": "PS-41",
    "title": "Smart Weather Alert System",
    "desc": "Users do not receive timely weather alerts. Build a system that sends alerts based on location.",
    "bullets": [
      "Location-based weather alerts",
      "Severe weather notification system"
    ]
  },
  {
    "id": "PS-42",
    "title": "Freelancer Project Management System",
    "desc": "Freelancers struggle to manage multiple projects. Build a platform to track projects and deadlines.",
    "bullets": [
      "Project tracking dashboard",
      "Deadline management & invoicing tools"
    ]
  },
  {
    "id": "PS-43",
    "title": "Campus Navigation System",
    "desc": "New students cannot easily find classrooms. Build a navigation system for campus locations.",
    "bullets": [
      "Interactive campus map",
      "Turn-by-turn navigation & search"
    ]
  },
  {
    "id": "PS-44",
    "title": "Online Poll and Survey System",
    "desc": "Organizations need quick feedback. Build a system to create and analyze polls.",
    "bullets": [
      "Poll & survey creation tool",
      "Real-time results & analytics dashboard"
    ]
  },
  {
    "id": "PS-45",
    "title": "Smart File Sharing System",
    "desc": "Sharing files securely is difficult. Build a secure file upload and sharing system.",
    "bullets": [
      "Encrypted file upload & sharing portal",
      "Access control & link expiration"
    ]
  },
  {
    "id": "PS-46",
    "title": "Motivation and Goal Tracking System",
    "desc": "Users struggle to track personal goals. Build a system to set and monitor goals.",
    "bullets": [
      "Goal setting & progress tracker",
      "Milestone alerts & motivational insights"
    ]
  },
  {
    "id": "PS-47",
    "title": "AI-Powered Fake News Detector",
    "desc": "Misinformation spreads rapidly on social media. Build a system that analyzes news articles and social media posts using NLP to classify them as real or fake, providing a credibility score and source verification.",
    "bullets": [
      "News credibility scoring engine",
      "Source cross-referencing & verification",
      "Browser extension for real-time detection"
    ]
  },
  {
    "id": "PS-48",
    "title": "Accessible Learning Platform for Differently-Abled",
    "desc": "Students with visual or hearing impairments face barriers in online education. Build an inclusive e-learning platform with text-to-speech, sign language video overlays, and customizable UI for various accessibility needs.",
    "bullets": [
      "Screen-reader compatible learning portal",
      "Sign language video overlay system",
      "Adaptive UI with accessibility controls"
    ]
  },
  {
    "id": "PS-49",
    "title": "Personal Finance Management System",
    "desc": "People struggle to manage their income, expenses, savings, and investments in one place. Build a comprehensive finance management platform that tracks transactions, categorizes spending, sets budget goals, and provides visual insights into financial health.",
    "bullets": [
      "Income & expense tracking dashboard",
      "Budget planning & savings goal tracker",
      "Spending analytics & financial reports"
    ]
  },
  {
    "id": "PS-50",
    "title": "Smart Travel Management Platform",
    "desc": "Planning trips involves juggling multiple apps for flights, hotels, itineraries, and budgets. Build a unified travel management system that helps users plan trips, create day-wise itineraries, track travel expenses, and get destination recommendations based on preferences and budget.",
    "bullets": [
      "Trip planner with day-wise itinerary builder",
      "Travel expense tracker & budget estimator",
      "Destination recommendation engine",
      "Open to all undergraduate students.",
      "Team Size: 1-4 members (inter-college & inter-specialization teams allowed).",
      "Industry-related Problem Statements will be provided.",
      "Problem statement selection.",
      "Submission of solution video & PPT for shortlisting.",
      "Grand Finale with live demos & presentations.",
      "Teams can propose their own problem statement.",
      "Strict deadlines; no late submissions allowed.",
      "Plagiarism will lead to immediate disqualification.",
      "Solutions are judged on: innovation, feasibility, scalability, technical execution, and presentation clarity."
    ]
  }
];
